
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 109
#define YY_END_OF_BUFFER 110
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[343] =
    {   0,
        0,    0,    0,    0,  110,  108,  107,  107,   95,  108,
      108,  101,   94,  108,   89,   90,   99,   98,   86,   97,
       93,  100,   54,   54,   87,   82,  102,   88,  103,  106,
       51,   51,   91,   92,  104,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   84,  105,   85,   96,  109,   81,    0,   59,
        0,    0,    1,   67,   85,   76,   68,    0,    0,   65,
       73,   63,   74,   64,   75,    0,   57,    2,   66,   58,
       53,    0,   54,    0,   54,   92,   83,   84,   91,   72,
       78,   80,   79,   71,   51,    0,    0,   69,   51,   51,

       51,   51,   51,   51,   51,   51,   51,   21,   51,   51,
       51,   51,   51,   51,   29,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   70,   77,   55,
       60,    0,   57,   57,    0,   58,   53,    0,   56,   52,
       62,   61,   51,   51,   51,   51,   51,   51,   51,   51,
       51,    5,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   27,   51,   51,   30,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,    0,   57,    0,   57,    0,   58,   56,
       52,   51,   51,   51,   51,   51,   51,   51,   51,   51,

       51,   13,   51,   15,   16,   51,   51,   51,   51,   23,
       24,   51,   51,   28,   51,   31,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   47,   51,
       51,    0,   57,   12,    4,   51,   51,   51,   51,   51,
       51,   51,   51,   14,   17,   51,   51,   51,   51,   26,
       51,   51,   51,   51,   34,   51,   51,   51,   51,   51,
       51,   51,   45,   51,   51,   50,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   22,   25,    8,
       51,   51,   33,   35,   37,   38,   39,   40,   51,   42,
       51,   51,    3,   51,   18,   51,   51,   51,   51,   51,

       51,   51,   20,    9,   51,   41,   51,   51,   51,   51,
       51,   51,   51,   43,   51,   19,   32,   46,   48,   51,
       51,   51,   51,   51,   51,   51,   51,   51,    7,   11,
       36,   44,   51,   51,   51,   51,   51,   51,   49,   10,
        6,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   27,   26,   26,   28,   29,
       30,   30,   30,   30,   30,   31,   30,   30,   30,   30,
       30,   30,   30,   30,   32,   30,   30,   33,   30,   30,
       34,   35,   36,   37,   38,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   30,   48,   49,   50,   51,
       52,   53,   30,   54,   55,   56,   57,   58,   59,   60,
       61,   62,   63,   64,   65,   66,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[67] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,    1,
        1,    1,    1,    1,    1,    3,    3,    3,    3,    4,
        4,    4,    4,    1,    1,    1,    1,    4,    3,    3,
        3,    3,    3,    3,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[349] =
    {   0,
        0,    0,    0,    0,  477,  478,  478,  478,  453,   62,
      472,   45,   62,  439,  478,  478,  450,   58,  478,   59,
       57,   65,   82,   75,  448,  450,   82,  447,   55,  478,
        0,   75,  478,  478,  446,   81,   35,  414,   70,   43,
       77,   47,  415,   76,  414,  413,  421,   87,  402,  411,
      409,  414,  478,   88,  478,  478,  478,  478,   82,  478,
      456,  455,  478,  478,  478,  478,  478,  103,  120,  478,
      478,  478,  478,  478,  478,  441,  122,  478,  478,  126,
      145,  165,  136,    0,  173,  478,  478,  478,  478,  433,
      478,  478,  478,  432,    0,  125,  419,  478,  401,  156,

      402,  395,  407,  394,  409,  396,  402,  388,  389,  386,
      386,  389,  386,  383,    0,  100,  387,  381,   91,  384,
      117,  120,  388,  381,  135,  149,  386,  478,  478,  478,
      478,  200,  478,  205,  213,  478,  189,  168,  221,  210,
      478,  478,  380,  151,  379,  370,  378,  385,  380,  365,
      373,    0,  372,  384,  379,  367,  153,  381,  379,  375,
      367,  373,  376,    0,  362,  366,    0,  367,  357,  363,
      352,  354,  356,  363,  349,  347,  347,  359,  349,  353,
      357,  359,  348,  225,  237,  245,  478,  243,  253,  478,
      242,  347,  345,  338,  342,  336,  342,  335,  344,  335,

      338,    0,  338,    0,    0,  329,  337,  326,  333,    0,
        0,  327,  324,    0,  328,    0,  339,  322,  322,  319,
      331,  321,  325,  330,  329,  106,  318,  323,    0,  311,
      323,  257,  259,    0,  327,  310,  308,  319,  314,  304,
      308,  315,  318,    0,    0,  305,  306,  311,  302,    0,
      309,  310,  294,  298,    0,  306,  303,  305,  289,  298,
      300,  298,    0,  290,  293,    0,  301,  291,  281,  285,
      284,  280,  290,  280,  275,  273,  273,    0,    0,    0,
      285,  284,    0,    0,    0,    0,    0,    0,  278,    0,
      264,  257,    0,  265,    0,  249,  258,  253,  256,  252,

      248,  251,    0,    0,  239,    0,  250,  246,  230,  238,
      245,  239,  241,  231,  208,    0,    0,    0,    0,  197,
      199,  209,  189,  199,  197,  186,  184,  174,    0,    0,
        0,    0,  179,  162,  143,  134,   97,   83,    0,    0,
        0,  478,  308,  312,  316,  320,  322,   69
    } ;

static yyconst flex_int16_t yy_def[349] =
    {   0,
      342,    1,  343,  343,  342,  342,  342,  342,  342,  344,
      345,  342,  342,  346,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      347,  347,  342,  342,  342,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  342,  342,  342,  342,  342,  342,  344,  342,
      344,  345,  342,  342,  342,  342,  342,  346,  346,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  348,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  347,  344,  346,  342,  347,  347,

      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  348,
      342,  342,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  342,  342,  342,  342,  342,  342,  342,
      342,  347,  347,  347,  347,  347,  347,  347,  347,  347,

      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  342,  342,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,

      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,    0,  342,  342,  342,  342,  342,  342
    } ;

static yyconst flex_int16_t yy_nxt[545] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   31,   31,   31,   31,
       32,   31,   31,   33,    6,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   31,   44,   31,   45,   31,
       46,   31,   31,   47,   48,   49,   50,   51,   52,   31,
       31,   31,   53,   54,   55,   56,   60,   64,   65,   66,
       71,  140,   76,   73,   77,   77,   78,   93,   94,   96,
       72,   74,   75,   97,   67,  107,   60,   79,   88,  101,
       80,  102,   85,   85,  108,  112,   61,   80,  113,   81,

       81,   89,   82,   90,   91,   83,   83,   99,  104,   82,
      128,  130,   83,   83,   84,  105,   61,   82,  100,  115,
      341,  106,  342,   83,   82,  109,  116,  110,   68,   60,
       83,   83,  120,  121,  340,  170,  111,   69,   83,   77,
       77,   84,  122,  134,  134,  123,  171,  261,  166,  132,
      133,  129,  133,  135,  136,  167,  136,  262,  175,   61,
       80,  173,   81,   81,  132,  133,   83,   83,  135,  136,
      133,  339,   82,  176,  136,  137,  137,  138,  174,  138,
      338,  179,  139,  139,   83,  139,  139,   82,   80,  180,
       85,   85,   83,  137,  144,  181,  145,  182,  146,  337,

       82,  137,  147,   83,   83,  193,  194,  206,  207,  148,
      149,  150,  184,  151,  184,   82,  336,  185,  185,  137,
      137,   83,  134,  134,  335,  188,  334,  188,  333,   83,
      189,  189,  186,  187,  332,  187,  331,  137,  139,  139,
      191,  191,  185,  185,  330,  137,  329,  186,  187,  190,
      328,  190,  327,  187,  185,  185,  326,  232,  191,  232,
      189,  189,  233,  233,  190,  133,  191,  133,  325,  190,
      189,  189,  191,  191,  233,  233,  233,  233,  324,  323,
      133,  136,  322,  136,  321,  133,  320,  187,  319,  187,
      191,  318,  317,  316,  315,  314,  136,  313,  191,  312,

      311,  136,  187,  310,  309,  308,  307,  187,   57,   57,
       57,   57,   59,   59,   59,   59,   62,   62,   62,   62,
       68,  306,   68,   68,   95,   95,  305,  304,  303,  302,
      301,  300,  299,  298,  297,  296,  295,  294,  293,  292,
      291,  290,  289,  288,  287,  286,  285,  284,  283,  282,
      281,  280,  279,  278,  277,  276,  275,  274,  273,  272,
      271,  270,  269,  268,  267,  266,  265,  264,  263,  260,
      259,  258,  257,  256,  255,  254,  253,  252,  251,  250,
      249,  248,  247,  246,  245,  244,  243,  242,  241,  240,
      239,  238,  237,  236,  235,  234,  231,  230,  229,  228,

      227,  226,  225,  224,  223,  222,  221,  220,  219,  218,
      217,  216,  215,  214,  213,  212,  211,  210,  209,  208,
      205,  204,  203,  202,  201,  200,  199,  198,  197,  196,
      195,  192,  183,  178,  177,  172,  169,  168,  165,  164,
      163,  162,  161,  160,  159,  158,  157,  156,  155,  154,
      153,  152,  143,   69,  142,  141,  131,   63,  342,  127,
      126,  125,  124,  119,  118,  117,  114,  103,   98,   92,
       87,   86,   70,   69,   63,   58,  342,    5,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,

      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342
    } ;

static yyconst flex_int16_t yy_chk[545] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   10,   12,   12,   13,
       18,  348,   21,   20,   21,   21,   22,   29,   29,   32,
       18,   20,   20,   32,   13,   40,   59,   22,   27,   37,
       24,   37,   24,   24,   40,   42,   10,   23,   42,   23,

       23,   27,   24,   27,   27,   24,   24,   36,   39,   23,
       54,   68,   23,   23,   23,   39,   59,   24,   36,   44,
      338,   39,   69,   24,   23,   41,   44,   41,   69,   96,
       23,   24,   48,   48,  337,  119,   41,   68,   23,   77,
       77,   23,   48,   80,   80,   48,  119,  226,  116,   77,
       77,   54,   77,   80,   80,  116,   80,  226,  122,   96,
       81,  121,   81,   81,   77,   77,   83,   83,   80,   80,
       77,  336,   81,  122,   80,   81,   81,   82,  121,   82,
      335,  125,   82,   82,   83,  138,  138,   81,   85,  125,
       85,   85,   83,   81,  100,  126,  100,  126,  100,  334,

       85,   81,  100,   85,   85,  144,  144,  157,  157,  100,
      100,  100,  132,  100,  132,   85,  333,  132,  132,  137,
      137,   85,  134,  134,  328,  135,  327,  135,  326,   85,
      135,  135,  134,  134,  325,  134,  324,  137,  139,  139,
      140,  140,  184,  184,  323,  137,  322,  134,  134,  139,
      321,  139,  320,  134,  185,  185,  315,  186,  140,  186,
      188,  188,  186,  186,  139,  185,  140,  185,  314,  139,
      189,  189,  191,  191,  232,  232,  233,  233,  313,  312,
      185,  189,  311,  189,  310,  185,  309,  233,  308,  233,
      191,  307,  305,  302,  301,  300,  189,  299,  191,  298,

      297,  189,  233,  296,  294,  292,  291,  233,  343,  343,
      343,  343,  344,  344,  344,  344,  345,  345,  345,  345,
      346,  289,  346,  346,  347,  347,  282,  281,  277,  276,
      275,  274,  273,  272,  271,  270,  269,  268,  267,  265,
      264,  262,  261,  260,  259,  258,  257,  256,  254,  253,
      252,  251,  249,  248,  247,  246,  243,  242,  241,  240,
      239,  238,  237,  236,  235,  231,  230,  228,  227,  225,
      224,  223,  222,  221,  220,  219,  218,  217,  215,  213,
      212,  209,  208,  207,  206,  203,  201,  200,  199,  198,
      197,  196,  195,  194,  193,  192,  183,  182,  181,  180,

      179,  178,  177,  176,  175,  174,  173,  172,  171,  170,
      169,  168,  166,  165,  163,  162,  161,  160,  159,  158,
      156,  155,  154,  153,  151,  150,  149,  148,  147,  146,
      145,  143,  127,  124,  123,  120,  118,  117,  114,  113,
      112,  111,  110,  109,  108,  107,  106,  105,  104,  103,
      102,  101,   99,   97,   94,   90,   76,   62,   61,   52,
       51,   50,   49,   47,   46,   45,   43,   38,   35,   28,
       26,   25,   17,   14,   11,    9,    5,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,

      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[110] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "parser-c.l"

#line 11 "parser-c.l"
#include <stdio.h>
#include "parser-c.tab.h"


void count();

struct ast {
    int nodetype;
    struct ast *l;
    struct ast *r;
};

struct term_id {
    int nodetype;
    struct ast *l;
    struct ast *r;
    char *name;
};

struct term_word {
    int nodetype;
    struct ast *l;
    struct ast *r;
    int wordtype;
};
struct term_num {
    int nodetype;
    struct ast *l;
    struct ast *r;
    int num;
};

struct term_op {
    int nodetype;
    struct ast *l;
    struct ast *r;
    int type;
};

struct symbol {
    char *name;
    struct ref *reflist;
    struct ast *func;
};

struct ref {
    struct ref *next;
    int type;
};

#define NHASH (9997)
struct symbol symtab[NHASH];

struct symbol *lookup(char*);
void addref(char*, int);

struct ast *new_ast(int nodetype, struct ast *l, struct ast *r);
struct ast *new_id(char *id);
struct ast *new_word(int word);
struct ast *new_struct(struct ast *struct_type, char *id, struct ast *spec_list);
struct ast *new_enum(char *id, struct ast * enum_list);

void parse_declaration(struct ast*); 
void print_tree (struct ast *a);
struct ast *find_id(struct ast *node);
struct ast *find_token(struct ast *a, int nodetype);

enum NODETYPE {
    NODE_DECLARATION,
    NODE_NUMBER,
    NODE_ID,
    NODE_WORD,
    NODE_RELOP,
    NODE_STRUCT,
    NODE_ENUM,
    NODE_DECLARATOR,
    NODE_DECLARATION_SPECIFIERS,
    NODE_INIT_DECLARATOR_LIST,
    NODE_INIT_DECLARATOR,
    NODE_TYPE_SPECIFIER,
    NODE_STRUCT_DECLARATION_LIST,
    NODE_STRUCT_DECLARATION,
    NODE_SPECIFIER_QUALIFIER_LIST,
    NODE_STRUCT_DECLARATOR_LIST,
    NODE_STRUCT_DECLARATOR,
    NODE_POINTER,
    NODE_TYPE_QUALIFIER,
    NODE_ASSIGNMENT_EXPRESSION,
    NODE_INITIALIZER_LIST,
    NODE_ENUMERATOR_LIST
};
#line 812 "lex.yy.c"

#define INITIAL 0
#define IFILE 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 103 "parser-c.l"

#line 1002 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 343 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 478 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 104 "parser-c.l"
{ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 105 "parser-c.l"
{ comment(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 106 "parser-c.l"
{ count(); return(ASM); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 107 "parser-c.l"
{ count(); return(ASM); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 108 "parser-c.l"
{ count(); return(ASM); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 109 "parser-c.l"
{ }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 110 "parser-c.l"
{ }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 111 "parser-c.l"
{ count(); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 112 "parser-c.l"
{ }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 113 "parser-c.l"
{ count(); return (ATTRIBUTE); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 114 "parser-c.l"
{ }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 115 "parser-c.l"
{ count(); return(INT); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 116 "parser-c.l"
{ count(); return(AUTO); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 117 "parser-c.l"
{ count(); return(BREAK); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 118 "parser-c.l"
{ count(); return(CASE); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 119 "parser-c.l"
{ count(); return(CHAR); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 120 "parser-c.l"
{ count(); return(CONST); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 121 "parser-c.l"
{ count(); return(CONST); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 122 "parser-c.l"
{ count(); return(CONTINUE); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 123 "parser-c.l"
{ count(); return(DEFAULT); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 124 "parser-c.l"
{ count(); return(DO); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 125 "parser-c.l"
{ count(); return(DOUBLE); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 126 "parser-c.l"
{ count(); return(ELSE); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 127 "parser-c.l"
{ count(); return(ENUM); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 128 "parser-c.l"
{ count(); return(EXTERN); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 129 "parser-c.l"
{ count(); return(FLOAT); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 130 "parser-c.l"
{ count(); return(FOR); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 131 "parser-c.l"
{ count(); return(GOTO); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 132 "parser-c.l"
{ count(); return(IF); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 133 "parser-c.l"
{ count(); return(INT); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 134 "parser-c.l"
{ count(); return(LONG); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 135 "parser-c.l"
{ count(); return(REGISTER); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 136 "parser-c.l"
{ count(); return(RETURN); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 137 "parser-c.l"
{ count(); return(SHORT); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 138 "parser-c.l"
{ count(); return(SIGNED); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 139 "parser-c.l"
{ count(); return(SIGNED); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 140 "parser-c.l"
{ count(); return(SIZEOF); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 141 "parser-c.l"
{ count(); return(STATIC); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 142 "parser-c.l"
{ count(); return(STRUCT); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 143 "parser-c.l"
{ count(); return(SWITCH); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 144 "parser-c.l"
{ count(); return(TYPEDEF); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 145 "parser-c.l"
{ count(); return(TYPEOF); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 146 "parser-c.l"
{ count(); return(TYPEOF); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 147 "parser-c.l"
{ count(); return(TYPEOF); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 148 "parser-c.l"
{ count(); return(UNION); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 149 "parser-c.l"
{ count(); return(UNSIGNED); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 150 "parser-c.l"
{ count(); return(VOID); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 151 "parser-c.l"
{ count(); return(VOLATILE); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 152 "parser-c.l"
{ count(); return(VOLATILE); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 153 "parser-c.l"
{ count(); return(WHILE); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 155 "parser-c.l"
{
				yylval.id = strdup(yytext);
				count(); 
				return(check_type());
			}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 161 "parser-c.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 162 "parser-c.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 163 "parser-c.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 164 "parser-c.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 166 "parser-c.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 167 "parser-c.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 168 "parser-c.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 170 "parser-c.l"
{ count(); return(STRING_LITERAL); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 172 "parser-c.l"
{ count(); return(ELLIPSIS); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 173 "parser-c.l"
{ count(); return(RIGHT_ASSIGN); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 174 "parser-c.l"
{ count(); return(LEFT_ASSIGN); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 175 "parser-c.l"
{ count(); return(ADD_ASSIGN); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 176 "parser-c.l"
{ count(); return(SUB_ASSIGN); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 177 "parser-c.l"
{ count(); return(MUL_ASSIGN); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 178 "parser-c.l"
{ count(); return(DIV_ASSIGN); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 179 "parser-c.l"
{ count(); return(MOD_ASSIGN); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 180 "parser-c.l"
{ count(); return(AND_ASSIGN); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 181 "parser-c.l"
{ count(); return(XOR_ASSIGN); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 182 "parser-c.l"
{ count(); return(OR_ASSIGN); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 183 "parser-c.l"
{ count(); return(RIGHT_OP); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 184 "parser-c.l"
{ count(); return(LEFT_OP); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 185 "parser-c.l"
{ count(); return(INC_OP); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 186 "parser-c.l"
{ count(); return(DEC_OP); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 187 "parser-c.l"
{ count(); return(PTR_OP); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 188 "parser-c.l"
{ count(); return(AND_OP); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 189 "parser-c.l"
{ count(); return(OR_OP); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 190 "parser-c.l"
{ count(); return(LE_OP); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 191 "parser-c.l"
{ count(); return(GE_OP); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 192 "parser-c.l"
{ count(); return(EQ_OP); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 193 "parser-c.l"
{ count(); return(NE_OP); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 194 "parser-c.l"
{ count(); return(';'); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 195 "parser-c.l"
{ count(); return(';'); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 196 "parser-c.l"
{ count(); return('{'); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 197 "parser-c.l"
{ count(); return('}'); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 198 "parser-c.l"
{ count(); return(','); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 199 "parser-c.l"
{ count(); return(':'); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 200 "parser-c.l"
{ count(); return('='); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 201 "parser-c.l"
{ count(); return('('); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 202 "parser-c.l"
{ count(); return(')'); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 203 "parser-c.l"
{ count(); return('['); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 204 "parser-c.l"
{ count(); return(']'); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 205 "parser-c.l"
{ count(); return('.'); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 206 "parser-c.l"
{ count(); return('&'); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 207 "parser-c.l"
{ count(); return('!'); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 208 "parser-c.l"
{ count(); return('~'); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 209 "parser-c.l"
{ count(); return('-'); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 210 "parser-c.l"
{ count(); return('+'); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 211 "parser-c.l"
{ count(); return('*'); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 212 "parser-c.l"
{ count(); return('/'); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 213 "parser-c.l"
{ count(); return('%'); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 214 "parser-c.l"
{ count(); return('<'); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 215 "parser-c.l"
{ count(); return('>'); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 216 "parser-c.l"
{ count(); return('^'); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 217 "parser-c.l"
{ count(); return('|'); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 218 "parser-c.l"
{ count(); return('?'); }
	YY_BREAK
case 107:
/* rule 107 can match eol */
YY_RULE_SETUP
#line 220 "parser-c.l"
{ count (); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 222 "parser-c.l"
{ /* ignore bad characters */ }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 224 "parser-c.l"
ECHO;
	YY_BREAK
#line 1648 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(IFILE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 343 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 343 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 342);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 224 "parser-c.l"




comment()
{
	char c, c1;

loop:
	while ((c = input()) != '*' && c != EOF)
		putchar(c);

	if ((c1 = input()) != '/' && c != EOF)
	{
		unput(c1);
		goto loop;
	}

	if (c != EOF)
		putchar(c1);
}

int column = 0;

void count()
{
	int i;

	for (i = 0; yytext[i] != '\0'; i++)
		if (yytext[i] == '\n')
			column = 0;
		else if (yytext[i] == '\t')
			column += 8 - (column % 8);
		else
			column++;
	ECHO;
}


int check_type()
{
    struct symbol *sp = lookup(yytext);
    if (sp->reflist && sp->reflist->type == TYPE_NAME) {
	return(TYPE_NAME);
    }
    return(IDENTIFIER);
}

static unsigned symhash(char *sym) 
{
    unsigned int hash = 0;
    unsigned c;
    while (c = *sym++) hash = hash * 9 ^ c;
    return hash;
}

struct symbol* lookup(char *sym) 
{
    struct symbol *sp = &symtab[symhash(sym)%NHASH];
    int scount = NHASH;
    
    while (--scount > 0) {
	if (sp->name && !strcmp(sp->name, sym)) 
	    return sp;
	if (!sp->name) {
	    sp->name = strdup(sym);
	    sp->reflist = 0;
	    return sp;
	}
	if (++sp >= symtab + NHASH)
	    sp = symtab;
    }
    fputs("symbol table overflow\n", stderr);
    abort();
}

void addref(char *word, int type)
{
    /*printf("%s:%d\n", word, type);*/
    struct ref *r;
    struct symbol *sp = lookup(word);
    if (sp->reflist) 
	return;
    r = malloc(sizeof(struct ref));
    if (!r) {
	fputs("out of space\n",stderr);
	abort();
    }
    r->next = sp->reflist;
    r->type = type;
    sp->reflist = r;
}
struct ast * new_ast(int nodetype, struct ast *l, struct ast *r) 
{
    struct ast *a = malloc(sizeof(struct ast));
    
    if (!a) {
	yyerror("out of memory");
	exit(0);
    }
    a->nodetype = nodetype;
    a->l = l;
    a->r = r;
    return a;
}

struct ast *new_id(char *id) 
{
    struct term_id *a = malloc(sizeof(struct term_id));
    if (!a) {
	yyerror("out of memory");
	exit(0);
    }
    a->nodetype = NODE_ID;
    a->name = strdup(id);
    /* add to symtable */
    a->l = NULL;
    a->r = NULL;
    return ((struct ast *) a);
}
struct ast *new_word(int word) 
{
    struct ast *a = malloc(sizeof(struct ast));
    if (!a) {
	yyerror("out of memory");
	exit(0);
    }
    a->nodetype = word;
    a->l = NULL;
    a->r = NULL;
    /* add to symtable */
    return a;
}
struct ast *new_struct(struct ast *struct_type, char* id, struct ast *spec_list) 
{
    struct ast *a = malloc(sizeof(struct ast));
    if (!a) {
	yyerror("out of memory");
	exit(0);
    }
    a->nodetype = NODE_STRUCT;
    a->l = NULL;
    a->r = NULL;
    /* add to symtable */
    return a;
}
struct ast *new_enum(char *id, struct ast * enum_list) 
{
    struct ast *a = malloc(sizeof(struct ast));
    if (!a) {
	yyerror("out of memory");
	exit(0);
    }
    a->nodetype = NODE_ENUM;
    a->l = NULL;
    a->r = NULL;
    /* add to symtable */
    return a;
}

void parse_declaration(struct ast* node) 
{
    /*print_tree(node);*/
    struct ast *tok;
    if (node->l != NULL) {
	tok = find_token(node->l, TYPEDEF);
    }
    if (tok != NULL && node->r != NULL) {
        struct term_id *a = (struct term_id *) find_id(node->r);
	if (a != NULL) {
	    /*printf("id:%s\n", a->name);*/
	    addref(a->name, TYPE_NAME);
	}
    }
}
struct ast* find_token(struct ast *node, int nodetype) 
{
    struct ast * a;
    if (node == NULL || node->nodetype == nodetype)
	return node;
    /*printf("test: %d\n", node->nodetype);*/
    a  = find_token(node->l, nodetype);
    if (a == NULL)
	a = find_token(node->r, nodetype);
    return a;
}
struct ast *find_id(struct ast *node) 
{
    struct ast * a;
    if (node == NULL || node->nodetype == NODE_ID)
	return node;
    a = find_id(node->l);
    if (a == NULL)
	a = find_id(node->r);
    return a;
}
void print_tree (struct ast *a) 
{
    if (a == NULL)
	return;
    printf("nodetype:%d\n", a->nodetype);
    if (a->nodetype == TYPEDEF)
	printf("begin typedef declaration\n");
    print_tree(a->l);
    print_tree(a->r);
}
